//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface Request {
    email?: string;
    password?: string;
}

export interface Request2 {
    email?: string;
    firstName?: string;
    lastName?: string;
    password?: string;
}

export interface Request3 {
    userId?: string;
    description?: string;
    dueDate?: Date | undefined;
    labels?: string[];
    priority?: number;
}